// <auto-generated />
using System;
using CrawlerDbPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrawlerServiceDbTools.DbMigration.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    [Migration("20260713133613_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrawlerDbModels.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<bool>("AutoCreateNextPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BatchId");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("CrawlerDbModels.BatchPart", b =>
                {
                    b.Property<int>("BpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime");

                    b.HasKey("BpId");

                    b.HasIndex("BatchId", "Created")
                        .IsUnique();

                    b.ToTable("BatchParts");
                });

            modelBuilder.Entity("CrawlerDbModels.ContentAnalysis", b =>
                {
                    b.Property<int>("CaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaId"));

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastModifiedDateOnServer")
                        .HasColumnType("datetime");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<int>("UrlId")
                        .HasColumnType("int");

                    b.HasKey("CaId");

                    b.HasIndex("UrlId");

                    b.HasIndex("BatchPartId", "UrlId")
                        .IsUnique();

                    b.ToTable("ContentsAnalysis");
                });

            modelBuilder.Entity("CrawlerDbModels.ExtensionModel", b =>
                {
                    b.Property<int>("ExtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtId"));

                    b.Property<string>("ExtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ExtProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ExtId");

                    b.HasIndex("ExtName")
                        .IsUnique();

                    b.ToTable("Extensions", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.HostByBatch", b =>
                {
                    b.Property<int>("HbbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HbbId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.HasKey("HbbId");

                    b.HasIndex("HostId");

                    b.HasIndex("SchemeId");

                    b.HasIndex("BatchId", "SchemeId", "HostId")
                        .IsUnique();

                    b.ToTable("HostsByBatches", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.HostModel", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostId"));

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("nvarchar(253)");

                    b.Property<bool>("HostProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("HostId");

                    b.HasIndex("HostName")
                        .IsUnique();

                    b.ToTable("Hosts", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.Robot", b =>
                {
                    b.Property<int>("RbtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RbtId"));

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<string>("RobotsTxt")
                        .HasColumnType("ntext");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.HasKey("RbtId");

                    b.HasIndex("HostId");

                    b.HasIndex("SchemeId");

                    b.HasIndex("BatchPartId", "SchemeId", "HostId")
                        .IsUnique();

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("CrawlerDbModels.SchemeModel", b =>
                {
                    b.Property<int>("SchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchId"));

                    b.Property<string>("SchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SchProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("SchId");

                    b.HasIndex("SchName")
                        .IsUnique();

                    b.ToTable("Schemes", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.TaskModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskName")
                        .IsUnique();

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.TaskStartPoint", b =>
                {
                    b.Property<int>("TspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TspId"));

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TspId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskStartPoints", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.Term", b =>
                {
                    b.Property<int>("TrmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrmId"));

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TermTypeId")
                        .HasColumnType("int")
                        .HasColumnName("termTypeId");

                    b.HasKey("TrmId");

                    b.HasIndex("TermText");

                    b.HasIndex("TermTypeId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("CrawlerDbModels.TermByUrl", b =>
                {
                    b.Property<int>("TbuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TbuId"));

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<int>("UrlId")
                        .HasColumnType("int");

                    b.HasKey("TbuId");

                    b.HasIndex("TermId");

                    b.HasIndex("UrlId");

                    b.HasIndex("BatchPartId", "UrlId", "Position")
                        .IsUnique();

                    b.ToTable("TermsByUrls", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.TermType", b =>
                {
                    b.Property<int>("TtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TtId"));

                    b.Property<string>("TtKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TtName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TtId");

                    b.HasIndex("TtKey")
                        .IsUnique();

                    b.ToTable("TermTypes");
                });

            modelBuilder.Entity("CrawlerDbModels.UrlGraphNode", b =>
                {
                    b.Property<int>("UgnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UgnId"));

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int");

                    b.Property<int>("FromUrlId")
                        .HasColumnType("int");

                    b.Property<int>("GotUrlId")
                        .HasColumnType("int");

                    b.HasKey("UgnId");

                    b.HasIndex("FromUrlId");

                    b.HasIndex("GotUrlId");

                    b.HasIndex("BatchPartId", "FromUrlId", "GotUrlId")
                        .IsUnique();

                    b.ToTable("UrlGraphNodes");
                });

            modelBuilder.Entity("CrawlerDbModels.UrlModel", b =>
                {
                    b.Property<int>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrlId"));

                    b.Property<int>("ExtensionId")
                        .HasColumnType("int");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSiteMap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.Property<int>("UrlHashCode")
                        .HasColumnType("int");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("UrlId");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("HostId");

                    b.HasIndex("SchemeId");

                    b.HasIndex("UrlHashCode", "HostId", "ExtensionId", "SchemeId");

                    b.ToTable("Urls", (string)null);
                });

            modelBuilder.Entity("CrawlerDbModels.BatchPart", b =>
                {
                    b.HasOne("CrawlerDbModels.Batch", "BatchNavigation")
                        .WithMany("BatchParts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.ContentAnalysis", b =>
                {
                    b.HasOne("CrawlerDbModels.BatchPart", "BatchPartNavigation")
                        .WithMany("ContentsAnalysis")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.UrlModel", "UrlNavigation")
                        .WithMany("ContentsAnalysis")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("UrlNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.HostByBatch", b =>
                {
                    b.HasOne("CrawlerDbModels.Batch", "BatchNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.HostModel", "HostNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.SchemeModel", "SchemeNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchNavigation");

                    b.Navigation("HostNavigation");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.Robot", b =>
                {
                    b.HasOne("CrawlerDbModels.BatchPart", "BatchPartNavigation")
                        .WithMany("Robots")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.HostModel", "HostNavigation")
                        .WithMany("Robots")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.SchemeModel", "SchemeNavigation")
                        .WithMany("Robots")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("HostNavigation");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.TaskStartPoint", b =>
                {
                    b.HasOne("CrawlerDbModels.TaskModel", "TaskNavigation")
                        .WithMany("StartPoints")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.Term", b =>
                {
                    b.HasOne("CrawlerDbModels.TermType", "TermTypeNavigation")
                        .WithMany("Terms")
                        .HasForeignKey("TermTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermTypeNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.TermByUrl", b =>
                {
                    b.HasOne("CrawlerDbModels.BatchPart", "BatchPartNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.Term", "TermNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.UrlModel", "UrlNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("TermNavigation");

                    b.Navigation("UrlNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.UrlGraphNode", b =>
                {
                    b.HasOne("CrawlerDbModels.BatchPart", "BatchPartNavigation")
                        .WithMany("UrlGraphNodes")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.UrlModel", "FromUrlNavigation")
                        .WithMany("UrlGraphNodesFrom")
                        .HasForeignKey("FromUrlId")
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.UrlModel", "GotUrlNavigation")
                        .WithMany("UrlGraphNodesGot")
                        .HasForeignKey("GotUrlId")
                        .IsRequired();

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("FromUrlNavigation");

                    b.Navigation("GotUrlNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.UrlModel", b =>
                {
                    b.HasOne("CrawlerDbModels.ExtensionModel", "ExtensionNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.HostModel", "HostNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrawlerDbModels.SchemeModel", "SchemeNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtensionNavigation");

                    b.Navigation("HostNavigation");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("CrawlerDbModels.Batch", b =>
                {
                    b.Navigation("BatchParts");

                    b.Navigation("HostsByBatches");
                });

            modelBuilder.Entity("CrawlerDbModels.BatchPart", b =>
                {
                    b.Navigation("ContentsAnalysis");

                    b.Navigation("Robots");

                    b.Navigation("TermsByUrls");

                    b.Navigation("UrlGraphNodes");
                });

            modelBuilder.Entity("CrawlerDbModels.ExtensionModel", b =>
                {
                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDbModels.HostModel", b =>
                {
                    b.Navigation("HostsByBatches");

                    b.Navigation("Robots");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDbModels.SchemeModel", b =>
                {
                    b.Navigation("HostsByBatches");

                    b.Navigation("Robots");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDbModels.TaskModel", b =>
                {
                    b.Navigation("StartPoints");
                });

            modelBuilder.Entity("CrawlerDbModels.Term", b =>
                {
                    b.Navigation("TermsByUrls");
                });

            modelBuilder.Entity("CrawlerDbModels.TermType", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("CrawlerDbModels.UrlModel", b =>
                {
                    b.Navigation("ContentsAnalysis");

                    b.Navigation("TermsByUrls");

                    b.Navigation("UrlGraphNodesFrom");

                    b.Navigation("UrlGraphNodesGot");
                });
#pragma warning restore 612, 618
        }
    }
}
